### ISSUE TITLE
ARM template: Custom deploy doesn't work

### ISSUE THREAD

**Issue by Lesrac** [Azure/azure-storage-av-automation#14]
## Expected Behavior
Inside an Azure Subscription, creating a resource group with a Storage account that has a one blob container.
Running the ARM script within the given subscription/resource group and setting the Storage account and the "Target Container" to the created blob container name.
Expecting to have all components deployed.

## Actual Behavior
The Review + create step fails with: {"code":"InvalidTemplateDeployment","details":[{"message":"Object reference not set to an instance of an object."}],"message":"The template deployment 'Microsoft.Template-20220831142402' is not valid according to the validation procedure. The tracking id is '52ecfcac-46d1-442c-9734-e5db6646a4f6'. See inner errors for details."}

## Steps to Reproduce the Problem
Prepare Azure subscription as defined in the Readmes Prerequisites.

Click the link in the Readme for "Deploy to Azure":
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-storage-av-automation%2Fmain%2FARM_template%2FAntivirusAutomationForStorageTemplate.json

Fill out mandatory fields.
Click "Review + create"

**Comment by t-ashitrit** [comment]
Hi @Lesrac thank you for reaching out.
I tried to deploy the template myself and it works as expected.

This system was designed to protect existing storage accounts as described in the [prerequisites](https://github.com/Azure/azure-storage-av-automation#prerequisites) section.

The option to create new resource group is usable when the storage account and the AV system are not in the same resource group, then you'll need to fill out `Subscription ID Of The Target Storage Account
` and `Name Of The Resource Group The Target Storage Account Belongs To` fields in the template deployment.

I'm closing this issue but feel free to reopen it if you have further questions or I miss understood your problem.
