### ISSUE TITLE
Deploy to existing VNET in another resource group

### ISSUE THREAD

**Issue by Tafikay** [Azure/azure-storage-av-automation#15]
## Describe the feature

Deploy to existing VNET in another resource group failed, need help!
{
    "status": "Failed",
    "error": {
        "code": "ResourceNotFound",
        "message": "The Resource 'Microsoft.Network/virtualNetworks/vnet' under resource group 'rgtest' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
    }
}
Anyone that can help me out?

**Comment by t-ashitrit** [comment]
Hi @Tafikay, thanks for reaching out.
Can you please share more details about your problem?
1. How did you tried to deploy the template?
2. Is the Vnet in the same subscription as the storage account?

**Comment by Tafikay** [comment]
Hey @t-ashitrit thank you very much for getting in touch.

1) Using the 'Deploy to Azure' existing vnet variation.
2) Yes, but it is in another resource group.

Edit: Fyi I don't have any ARM experience, I always use Terraform myself.

**Comment by t-ashitrit** [comment]
Hi @Tafikay, I looked into your case, and I think there is no option in ARM to create a child resource (subnet) when the parent resource (vnet) is in another resource group, which means that in order for this to work the deployment of this template has to be to the same resource group as the vnet (the storage account can still be located in another resource group).

I'll try to look for a different solution but for no this should fix your error.

**Comment by Tafikay** [comment]
Hey @t-ashitrit I was able to play around with the ARM template and deployed it by using the following variables:
       "ExistingVnetId": "[resourceId(parameters('virtualNetworkResourceGroup'),'Microsoft.Network/virtualNetworks',parameters('existingVnetName'))]",
        "VmSubnetId": "[concat(variables('ExistingVnetId'),'/subnets/',variables('vmSubnetName'))]",
        "FunctionSubnetId": "[concat(variables('ExistingVnetId'),'/subnets/',variables('functionSubnetName'))]"

I added the following code to the NIC
"subnet": {
 "id": "[variables('VmSubnetId')]"
 }

And something similar for the functionapp.

Thanks!

**Comment by TylerPadrao** [comment]
Hi there, this fix is exactly what I am looking for. @Tafikay where did you exactly add the FunctionSubnetId variable for the function app? I know there is a few places where there are function app subnets in the ARM template. Sorry, I am a bit new to ARM templates. Any insight would be helpful. Thanks!

**Comment by Tafikay** [comment]
hi @TylerPadrao unfortunately I had this ARM script on a customer laptop which I no longer have access to. You'll have to figure it out with the information in my previous comment. Additionally if you're looking to implement this solution, I advise you to look into Microsoft Defender for storage which these days has packet inspection for blob storage.

**Comment by t-ashitrit** [comment]
Hi, I tried to recreate @Tafikay solution, but it seems that in order for this to work the Vnet and the Subnets should be created before deploying the Av-Automation template.

Here's a few steps to implement the solution to your problem:
1. Create the Vnet, NetworkSecurityGroup and subnets.
2. Remove the creation steps of those resources from the ARM template.
3. Add the new subnets resource id's to the template, one to the VM network interface and one to the function app deployment
Example:
VM network interface:
```
{
            "type": "Microsoft.Network/networkInterfaces",
            "name": "[variables('vmNetworkInterfateworkInterfaceName')]",
            "apiVersion": "2020-06-01",
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[variables('publicIPAddressName')]",
                "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('existingVnetName'), variables('vmSubnetName'))]" // remove this dependency.
            ],
            "properties": {
                "ipConfigurations": [
                    {
                        "name": "ipconfig1",
                        "properties": {
                            "publicIPAddress": "[if(parameters('addPublicIPToVM'), variables('publicIpId'), json('null'))]",
                            "subnet": {
                                "id": "<The new subnet resource id>"
                            }
                        }
                    }
                ]
            }
        },
```

Function app:
```
{
            "type": "Microsoft.Web/sites",
            "name": "[variables('functionAppName')]",
            "apiVersion": "2020-09-01",
            "location": "[resourceGroup().location]",
            "kind": "functionapp",
            "dependsOn": [
                "[resourceId('Microsoft.Web/serverfarms', variables('appServicePlanName'))]"
            ],
            "identity": {
                "type": "SystemAssigned"
            },
            "properties": {
                "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('appServicePlanName'))]",
                "siteConfig": {
                    "alwaysOn": true,
                    "use32BitWorkerProcess": false
                }
            },
            "resources": [
                {
                    "type": "config",
                    "name": "virtualNetwork",
                    "apiVersion": "2019-08-01",
                    "dependsOn": [
                        "[resourceId('Microsoft.Web/sites', variables('functionAppName'))]",
                        "[resourceId('Microsoft.Storage/storageAccounts', variables('functionHostStorageAccountName'))]",
                        "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('existingVnetName'), variables('functionSubnetName'))]"
                    ],
                    "properties": {
                        "subnetResourceId": <The new subnet resource id>",
                        "swiftSupported": true
                    }
                },
}
```

Let me know if you succeeded.
