### ISSUE TITLE
Existing Vnet must be in same resource group?

### ISSUE THREAD

**Issue by TylerPadrao** [Azure/azure-storage-av-automation#22]
Hi there, I am trying to deploy using the custom template that allows you to use an existing vnet. It looks like the existing vnet must be within the same resource group. Is there anyway I can deploy the custom template to use a vnet in a different resource group?

**Comment by t-ashitrit** [comment]
Hi, sorry for the delayed response.
Please refer to [issue #15](https://github.com/Azure/azure-storage-av-automation/issues/15), lets continue the discussion there.
Closing this one.
