### ISSUE TITLE
Any plans to provide an ARM template which will deploy the solution to VMScaleset

### ISSUE THREAD

**Issue by manikandanramaswami** [Azure/azure-storage-av-automation#3]
Thanks for a neat solution to perform AV scanning. Are there any plans to provide a deployment template which enables VM Scaleset deployment of Antivirus Solution behind a load balancer? This might be a required scenario in terms of availability and scalability of the solution.

**Comment by t-ashitrit** [comment]
At the moment there are no plans to implement this scenario. Here's a [link](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/quick-create-portal) to Azure Vm Scale Set Quickstart guide, you can go ahead and try to implement it yourself.
