### ISSUE TITLE
ARM Template deploys with .NET version 6.0.0

### ISSUE THREAD

**Issue by AdrianThomas12** [Azure/azure-storage-av-automation#5]
## Expected Behavior

Deploy ARM Template and core setup to work

## Actual Behavior

Took a bit of digging, but the VM deploys with the latest version of .NET - 6.0.0.

Manually changed the version of .NET to PowerShell script downloads to 5.0.0 worked as expected.

WebService doesn't start

## Steps to Reproduce the Problem

Deploy ARM template

**Comment by t-ashitrit** [comment]
Thanks for finding this bug (and the solution).
I uploaded a new version with fixed dotnet version (5.0) you can redeploy with latest release and it should be fixed.
