### ISSUE TITLE
Issues with manual deployment via BuildAndDeploy.ps1 script

### ISSUE THREAD

**Issue by grnut** [Azure/azure-storage-av-automation#7]
Hi Devs, I've been having problems running the BuildAndDeploy.ps1 script to deploy my modified solution. I first had to make the following changes to the parameters at the bottom of the script to match the parameter names in the template, was I right to do this or am I missing something?
![image](https://user-images.githubusercontent.com/93314132/144409041-4a75509c-9cc6-4e50-a870-e113577140ca.png)

Once I get the script running, the deployments fails at the  {VM name}/VmInitScript step with the following error: 

> {
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'VmInitScript'. Error message: \"Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
    }

Because it fails at this stage I can't SSH/RDP/Bastion into the VM to check the error log and find exactly what went wrong. I also didn't get this error deploying to the same subscription when using the "Deploy to Azure" button linked in step 1 of the project's README file so I'm not sure what is going wrong here. Is this an error you are familiar with? I only need to make some small changes to the solution, so any assistance you could offer would be great. Thanks

**Comment by t-ashitrit** [comment]
Thanks @grnut for reaching out and opening this Issue.
1. Template parameters names - the parameters in the script should match the template parameters and I upload another version of that script with matching parameters names.
2. File not found bug - please check your source code container and make sure that it has "blob access" level.
    -   You can try to download one of the blobs with your browser to check the access level using:
         https://(storage-account-name).blob.core.windows.net/(source-code-container)/ScanHttpServer.zip
    -  You can use new container name for the source code container and the script will create it for you with the correct configuration.

Please delete the VM resource that the script created and redeploy the service after validating the source code container access level.

**Comment by t-ashitrit** [comment]
Closing this issue, please reopen if you have any more question on the matter
