### ISSUE TITLE
"Error parsing template" when deploying to Azure

### ISSUE THREAD

**Issue by scrouet-neocase** [Azure/azure-storage-av-automation#9]
## Expected Behavior

I tried to deploy the ARM template with the "Deploy to Azure" button.

## Actual Behavior

A new tab titled "Custom deployment" with URL "https://portal.azure.com/#create/Microsoft.Template" opened and it failed immediately with the error "Error parsing template. Please ensure template is valid JSON. Property name expected at character position 5094. (1 other errors)"

## Steps to Reproduce the Problem

Just click the first "Deploy to Azure" button

**Comment by t-ashitrit** [comment]
Hello [scrouet-neocase](https://github.com/scrouet-neocase),
Thank you for opening this issue!
The error was a simple misplaced comma in the template, I fixed the bug and you can go ahead and try again.
I'm closing this issue but feel free to reopen it if something goes wrong.
